### ISSUE TITLE
Follower and followings lists

### ISSUE THREAD

**Issue by ahmetdadak** [bounswe/bounswe2020group7#176] opened 2020-11-25 15:40 UTC
Can you provide an endpoint that takes get requests and return followers and followings list of the user ids?

**Comment by HUmutOzdemir** [comment] 2020-11-25 17:15
I think it can be better to add this information to the existing endpoints

**Comment by cakmadam98** [comment] 2020-11-25 17:45
Existing API's return user_id's with other informations such as name and e-mail. You only want to get user_id's, right?

**Comment by ahmetdadak** [comment] 2020-11-27 22:10
@cakmadam98 yes, you are right, it was definitely what I mean. I would be great if you can provide it, but it is not high priority, I can handle it in frontend but it makes run website more efficient if there is such an feature also.

**Comment by HUmutOzdemir** [comment] 2020-12-01 12:34
Add is_private and follow_state to the get user endpoints.

Deadline: @05.12.2020

**Comment by alperendivriklioglu** [comment] 2020-12-07 04:35
This issue is the duplicate of #195, if I understand it right. So, this will be resolved after the pull request #218 gets merged.

**Closed** 2020-12-16 15:28 UTC
Labels: Priority: Low, Subteam: Backend
